# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flownote/ui/widgets/preferences_ui.ui'
#
# Created: Thu Apr 13 15:59:31 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(414, 339)
        self.verticalLayout = QtWidgets.QVBoxLayout(Preferences)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab = QtWidgets.QTabWidget(Preferences)
        self.tab.setObjectName("tab")
        self.widget_2 = QtWidgets.QWidget()
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chkAutoSave = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkAutoSave.setEnabled(False)
        self.chkAutoSave.setObjectName("chkAutoSave")
        self.verticalLayout_2.addWidget(self.chkAutoSave)
        self.chkOpenLast = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkOpenLast.setObjectName("chkOpenLast")
        self.verticalLayout_2.addWidget(self.chkOpenLast)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spnWordsMinSize = QtWidgets.QSpinBox(self.groupBox)
        self.spnWordsMinSize.setObjectName("spnWordsMinSize")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spnWordsMinSize)
        self.txtWordsExclude = QtWidgets.QLineEdit(self.groupBox)
        self.txtWordsExclude.setObjectName("txtWordsExclude")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.txtWordsExclude)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label_2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.tab.addTab(self.widget_2, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lstTags = QtWidgets.QListWidget(self.tab_2)
        self.lstTags.setObjectName("lstTags")
        self.verticalLayout_4.addWidget(self.lstTags)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnTagRemove = QtWidgets.QPushButton(self.tab_2)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.btnTagRemove.setIcon(icon)
        self.btnTagRemove.setFlat(True)
        self.btnTagRemove.setObjectName("btnTagRemove")
        self.horizontalLayout.addWidget(self.btnTagRemove)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblTag = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTag.setFont(font)
        self.lblTag.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTag.setObjectName("lblTag")
        self.horizontalLayout_4.addWidget(self.lblTag)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnColor = QtWidgets.QPushButton(self.widget)
        self.btnColor.setObjectName("btnColor")
        self.horizontalLayout_2.addWidget(self.btnColor)
        self.btnClearColor = QtWidgets.QPushButton(self.widget)
        self.btnClearColor.setText("")
        icon = QtGui.QIcon.fromTheme("edit-clear")
        self.btnClearColor.setIcon(icon)
        self.btnClearColor.setFlat(True)
        self.btnClearColor.setObjectName("btnClearColor")
        self.horizontalLayout_2.addWidget(self.btnClearColor)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnTextColor = QtWidgets.QPushButton(self.widget)
        self.btnTextColor.setObjectName("btnTextColor")
        self.horizontalLayout_3.addWidget(self.btnTextColor)
        self.btnClearTextColor = QtWidgets.QPushButton(self.widget)
        self.btnClearTextColor.setText("")
        icon = QtGui.QIcon.fromTheme("edit-clear")
        self.btnClearTextColor.setIcon(icon)
        self.btnClearTextColor.setFlat(True)
        self.btnClearTextColor.setObjectName("btnClearTextColor")
        self.horizontalLayout_3.addWidget(self.btnClearTextColor)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnBorderColor = QtWidgets.QPushButton(self.widget)
        self.btnBorderColor.setObjectName("btnBorderColor")
        self.horizontalLayout_5.addWidget(self.btnBorderColor)
        self.btnClearBorderColor = QtWidgets.QPushButton(self.widget)
        self.btnClearBorderColor.setText("")
        icon = QtGui.QIcon.fromTheme("edit-clear")
        self.btnClearBorderColor.setIcon(icon)
        self.btnClearBorderColor.setFlat(True)
        self.btnClearBorderColor.setObjectName("btnClearBorderColor")
        self.horizontalLayout_5.addWidget(self.btnClearBorderColor)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_6.addWidget(self.widget)
        self.tab.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tab)

        self.retranslateUi(Preferences)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):
        _translate = QtCore.QCoreApplication.translate
        Preferences.setWindowTitle(_translate("Preferences", "Preferences"))
        self.groupBox_2.setTitle(_translate("Preferences", "General"))
        self.chkAutoSave.setText(_translate("Preferences", "Auto save"))
        self.chkOpenLast.setText(_translate("Preferences", "Open last notebooks on startup"))
        self.groupBox.setTitle(_translate("Preferences", "Clouds"))
        self.label.setText(_translate("Preferences", "Minimum size words:"))
        self.label_2.setText(_translate("Preferences", "Exclude those words (coma speparated):"))
        self.tab.setTabText(self.tab.indexOf(self.widget_2), _translate("Preferences", "General"))
        self.btnTagRemove.setText(_translate("Preferences", "Remove custom tag"))
        self.lblTag.setText(_translate("Preferences", "Tag"))
        self.btnColor.setText(_translate("Preferences", "Color"))
        self.btnTextColor.setText(_translate("Preferences", "Text color"))
        self.btnBorderColor.setText(_translate("Preferences", "Border"))
        self.tab.setTabText(self.tab.indexOf(self.tab_2), _translate("Preferences", "Tags"))

