# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flownote/ui/mainWindow_ui.ui'
#
# Created: Fri Mar 31 00:18:04 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(954, 779)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tab = QTabBar(self.centralwidget)
        self.tab.setObjectName("tab")
        self.verticalLayout_5.addWidget(self.tab)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.filter = QtWidgets.QWidget(self.splitter)
        self.filter.setObjectName("filter")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.filter)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setObjectName("topLayout")
        self.btnNewNotebook = QtWidgets.QToolButton(self.filter)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.btnNewNotebook.setIcon(icon)
        self.btnNewNotebook.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnNewNotebook.setAutoRaise(True)
        self.btnNewNotebook.setObjectName("btnNewNotebook")
        self.topLayout.addWidget(self.btnNewNotebook)
        self.btnPrevious = QtWidgets.QToolButton(self.filter)
        icon = QtGui.QIcon.fromTheme("go-previous")
        self.btnPrevious.setIcon(icon)
        self.btnPrevious.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnPrevious.setAutoRaise(True)
        self.btnPrevious.setObjectName("btnPrevious")
        self.topLayout.addWidget(self.btnPrevious)
        self.btnNext = QtWidgets.QToolButton(self.filter)
        icon = QtGui.QIcon.fromTheme("go-next")
        self.btnNext.setIcon(icon)
        self.btnNext.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnNext.setAutoRaise(True)
        self.btnNext.setObjectName("btnNext")
        self.topLayout.addWidget(self.btnNext)
        self.btnSave = QtWidgets.QToolButton(self.filter)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.btnSave.setIcon(icon)
        self.btnSave.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnSave.setAutoRaise(True)
        self.btnSave.setObjectName("btnSave")
        self.topLayout.addWidget(self.btnSave)
        self.verticalLayout_2.addLayout(self.topLayout)
        self.grpNotebooks = QtWidgets.QGroupBox(self.filter)
        self.grpNotebooks.setFlat(True)
        self.grpNotebooks.setObjectName("grpNotebooks")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.grpNotebooks)
        self.horizontalLayout_2.setContentsMargins(0, 6, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lstNotebooks = QtWidgets.QListWidget(self.grpNotebooks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstNotebooks.sizePolicy().hasHeightForWidth())
        self.lstNotebooks.setSizePolicy(sizePolicy)
        self.lstNotebooks.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.lstNotebooks.setObjectName("lstNotebooks")
        item = QtWidgets.QListWidgetItem()
        self.lstNotebooks.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstNotebooks.addItem(item)
        self.horizontalLayout_2.addWidget(self.lstNotebooks)
        self.verticalLayout_2.addWidget(self.grpNotebooks)
        self.calendar = QtWidgets.QCalendarWidget(self.filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendar.sizePolicy().hasHeightForWidth())
        self.calendar.setSizePolicy(sizePolicy)
        self.calendar.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendar.setNavigationBarVisible(True)
        self.calendar.setDateEditEnabled(True)
        self.calendar.setObjectName("calendar")
        self.verticalLayout_2.addWidget(self.calendar)
        self.groupBox = QtWidgets.QGroupBox(self.filter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.txtFilter = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtFilter.sizePolicy().hasHeightForWidth())
        self.txtFilter.setSizePolicy(sizePolicy)
        self.txtFilter.setClearButtonEnabled(True)
        self.txtFilter.setObjectName("txtFilter")
        self.verticalLayout_4.addWidget(self.txtFilter)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout.addWidget(self.dateEdit_2, 0, 3, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.lstTags = cloudView(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstTags.sizePolicy().hasHeightForWidth())
        self.lstTags.setSizePolicy(sizePolicy)
        self.lstTags.setObjectName("lstTags")
        self.verticalLayout_4.addWidget(self.lstTags)
        self.lstWords = cloudView(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstWords.sizePolicy().hasHeightForWidth())
        self.lstWords.setSizePolicy(sizePolicy)
        self.lstWords.setObjectName("lstWords")
        self.verticalLayout_4.addWidget(self.lstWords)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.grpNotes = QtWidgets.QGroupBox(self.filter)
        self.grpNotes.setObjectName("grpNotes")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.grpNotes)
        self.verticalLayout_3.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tblList = QtWidgets.QTableWidget(self.grpNotes)
        self.tblList.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tblList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblList.setShowGrid(False)
        self.tblList.setWordWrap(False)
        self.tblList.setObjectName("tblList")
        self.tblList.setColumnCount(3)
        self.tblList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblList.setHorizontalHeaderItem(2, item)
        self.tblList.horizontalHeader().setVisible(False)
        self.tblList.verticalHeader().setVisible(False)
        self.tblList.verticalHeader().setDefaultSectionSize(20)
        self.verticalLayout_3.addWidget(self.tblList)
        self.verticalLayout_2.addWidget(self.grpNotes)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnToggleNotebooks = QtWidgets.QToolButton(self.filter)
        icon = QtGui.QIcon.fromTheme("folder")
        self.btnToggleNotebooks.setIcon(icon)
        self.btnToggleNotebooks.setCheckable(True)
        self.btnToggleNotebooks.setChecked(True)
        self.btnToggleNotebooks.setAutoRaise(True)
        self.btnToggleNotebooks.setObjectName("btnToggleNotebooks")
        self.horizontalLayout.addWidget(self.btnToggleNotebooks)
        self.btnToggleFilter = QtWidgets.QToolButton(self.filter)
        icon = QtGui.QIcon.fromTheme("edit-find")
        self.btnToggleFilter.setIcon(icon)
        self.btnToggleFilter.setCheckable(True)
        self.btnToggleFilter.setChecked(True)
        self.btnToggleFilter.setAutoRaise(True)
        self.btnToggleFilter.setObjectName("btnToggleFilter")
        self.horizontalLayout.addWidget(self.btnToggleFilter)
        self.btnToggleCalendar = QtWidgets.QToolButton(self.filter)
        icon = QtGui.QIcon.fromTheme("x-office-calendar")
        self.btnToggleCalendar.setIcon(icon)
        self.btnToggleCalendar.setCheckable(True)
        self.btnToggleCalendar.setChecked(True)
        self.btnToggleCalendar.setAutoRaise(True)
        self.btnToggleCalendar.setObjectName("btnToggleCalendar")
        self.horizontalLayout.addWidget(self.btnToggleCalendar)
        self.btnToggleTags = QtWidgets.QToolButton(self.filter)
        icon = QtGui.QIcon.fromTheme("task-past-due")
        self.btnToggleTags.setIcon(icon)
        self.btnToggleTags.setCheckable(True)
        self.btnToggleTags.setChecked(True)
        self.btnToggleTags.setAutoRaise(True)
        self.btnToggleTags.setObjectName("btnToggleTags")
        self.horizontalLayout.addWidget(self.btnToggleTags)
        self.btnToggleWords = QtWidgets.QToolButton(self.filter)
        icon = QtGui.QIcon.fromTheme("system-search")
        self.btnToggleWords.setIcon(icon)
        self.btnToggleWords.setCheckable(True)
        self.btnToggleWords.setChecked(True)
        self.btnToggleWords.setAutoRaise(True)
        self.btnToggleWords.setObjectName("btnToggleWords")
        self.horizontalLayout.addWidget(self.btnToggleWords)
        self.btnToggleList = QtWidgets.QToolButton(self.filter)
        icon = QtGui.QIcon.fromTheme("view-sort-ascending")
        self.btnToggleList.setIcon(icon)
        self.btnToggleList.setCheckable(True)
        self.btnToggleList.setChecked(True)
        self.btnToggleList.setAutoRaise(True)
        self.btnToggleList.setObjectName("btnToggleList")
        self.horizontalLayout.addWidget(self.btnToggleList)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.editor = QtWidgets.QStackedWidget(self.splitter)
        self.editor.setObjectName("editor")
        self.editorPage1 = QtWidgets.QWidget()
        self.editorPage1.setObjectName("editorPage1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.editorPage1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text = QtWidgets.QTextEdit(self.editorPage1)
        self.text.setObjectName("text")
        self.verticalLayout.addWidget(self.text)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txtNoteName = QtWidgets.QLineEdit(self.editorPage1)
        self.txtNoteName.setObjectName("txtNoteName")
        self.horizontalLayout_3.addWidget(self.txtNoteName)
        self.dateNoteDate = QtWidgets.QDateEdit(self.editorPage1)
        self.dateNoteDate.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateNoteDate.setCalendarPopup(True)
        self.dateNoteDate.setObjectName("dateNoteDate")
        self.horizontalLayout_3.addWidget(self.dateNoteDate)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.editor.addWidget(self.editorPage1)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scroll = scrollView(self.page)
        self.scroll.setWidgetResizable(True)
        self.scroll.setObjectName("scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 581, 683))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scroll)
        self.editor.addWidget(self.page)
        self.verticalLayout_5.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 954, 20))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Journal = QtWidgets.QAction(MainWindow)
        self.actionOpen_Journal.setObjectName("actionOpen_Journal")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionClose_current_journal = QtWidgets.QAction(MainWindow)
        self.actionClose_current_journal.setObjectName("actionClose_current_journal")
        self.action_New_Journal = QtWidgets.QAction(MainWindow)
        self.action_New_Journal.setObjectName("action_New_Journal")
        self.action_Recent_Journals = QtWidgets.QAction(MainWindow)
        self.action_Recent_Journals.setObjectName("action_Recent_Journals")
        self.menu_File.addAction(self.action_New_Journal)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionOpen_Journal)
        self.menu_File.addAction(self.action_Recent_Journals)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionClose_current_journal)
        self.menu_File.addAction(self.actionQuit)
        self.menu_Edit.addAction(self.actionPreferences)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())

        self.retranslateUi(MainWindow)
        self.editor.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnNewNotebook.setText(_translate("MainWindow", "New Note"))
        self.btnPrevious.setText(_translate("MainWindow", "Previous"))
        self.btnNext.setText(_translate("MainWindow", "Next"))
        self.btnSave.setText(_translate("MainWindow", "Save"))
        self.grpNotebooks.setTitle(_translate("MainWindow", "Notebooks"))
        __sortingEnabled = self.lstNotebooks.isSortingEnabled()
        self.lstNotebooks.setSortingEnabled(False)
        item = self.lstNotebooks.item(0)
        item.setText(_translate("MainWindow", "All"))
        item = self.lstNotebooks.item(1)
        item.setText(_translate("MainWindow", "One"))
        self.lstNotebooks.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("MainWindow", "Filters"))
        self.label.setText(_translate("MainWindow", "From:"))
        self.label_2.setText(_translate("MainWindow", "To:"))
        self.grpNotes.setTitle(_translate("MainWindow", "Notes"))
        self.tblList.setSortingEnabled(True)
        item = self.tblList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tblList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tblList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "WC"))
        self.btnToggleNotebooks.setText(_translate("MainWindow", "Notebooks"))
        self.btnToggleFilter.setText(_translate("MainWindow", "Filter"))
        self.btnToggleCalendar.setText(_translate("MainWindow", "Calendar"))
        self.btnToggleTags.setText(_translate("MainWindow", "Tags"))
        self.btnToggleWords.setText(_translate("MainWindow", "Words"))
        self.btnToggleList.setText(_translate("MainWindow", "List"))
        self.dateNoteDate.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit"))
        self.actionOpen_Journal.setText(_translate("MainWindow", "&Open Journal"))
        self.actionOpen_Journal.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionPreferences.setText(_translate("MainWindow", "&Preferences"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionClose_current_journal.setText(_translate("MainWindow", "&Close current journal"))
        self.actionClose_current_journal.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.action_New_Journal.setText(_translate("MainWindow", "&New Journal"))
        self.action_Recent_Journals.setText(_translate("MainWindow", "&Recent Journals"))

from PyQt5.QtWidgets import QTabBar
from flownote.ui.views.cloudView import cloudView
from flownote.ui.views.scrollView import scrollView
